/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlangroupIndexRouteImport } from './routes/plangroup/index'
import { Route as PlangroupPlanRouteImport } from './routes/plangroup/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlangroupIndexRoute = PlangroupIndexRouteImport.update({
  id: '/plangroup/',
  path: '/plangroup/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlangroupPlanRoute = PlangroupPlanRouteImport.update({
  id: '/plangroup/plan',
  path: '/plangroup/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/plangroup': typeof PlangroupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/plangroup': typeof PlangroupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/plangroup/': typeof PlangroupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plangroup/plan' | '/plangroup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plangroup/plan' | '/plangroup'
  id: '__root__' | '/' | '/plangroup/plan' | '/plangroup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlangroupPlanRoute: typeof PlangroupPlanRoute
  PlangroupIndexRoute: typeof PlangroupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plangroup/': {
      id: '/plangroup/'
      path: '/plangroup'
      fullPath: '/plangroup'
      preLoaderRoute: typeof PlangroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plangroup/plan': {
      id: '/plangroup/plan'
      path: '/plangroup/plan'
      fullPath: '/plangroup/plan'
      preLoaderRoute: typeof PlangroupPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlangroupPlanRoute: PlangroupPlanRoute,
  PlangroupIndexRoute: PlangroupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
