/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as PlangroupIndexRouteImport } from './routes/plangroup/index'
import { Route as SignupSuccessRouteImport } from './routes/signup/success'
import { Route as PlangroupPlanRouteImport } from './routes/plangroup/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlangroupIndexRoute = PlangroupIndexRouteImport.update({
  id: '/plangroup/',
  path: '/plangroup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup/success',
  path: '/signup/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PlangroupPlanRoute = PlangroupPlanRouteImport.update({
  id: '/plangroup/plan',
  path: '/plangroup/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/signup/success': typeof SignupSuccessRoute
  '/plangroup': typeof PlangroupIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/signup/success': typeof SignupSuccessRoute
  '/plangroup': typeof PlangroupIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plangroup/plan': typeof PlangroupPlanRoute
  '/signup/success': typeof SignupSuccessRoute
  '/plangroup/': typeof PlangroupIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plangroup/plan'
    | '/signup/success'
    | '/plangroup'
    | '/signin'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plangroup/plan'
    | '/signup/success'
    | '/plangroup'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/plangroup/plan'
    | '/signup/success'
    | '/plangroup/'
    | '/signin/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlangroupPlanRoute: typeof PlangroupPlanRoute
  SignupSuccessRoute: typeof SignupSuccessRoute
  PlangroupIndexRoute: typeof PlangroupIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plangroup/': {
      id: '/plangroup/'
      path: '/plangroup'
      fullPath: '/plangroup'
      preLoaderRoute: typeof PlangroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/success': {
      id: '/signup/success'
      path: '/signup/success'
      fullPath: '/signup/success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plangroup/plan': {
      id: '/plangroup/plan'
      path: '/plangroup/plan'
      fullPath: '/plangroup/plan'
      preLoaderRoute: typeof PlangroupPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlangroupPlanRoute: PlangroupPlanRoute,
  SignupSuccessRoute: SignupSuccessRoute,
  PlangroupIndexRoute: PlangroupIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
